/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.dis.practica8;

import java.awt.Dimension;
import java.io.File;

/**
 *
 * @author Andres
 */
public class InternalWindow extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalWindow
     */
    public InternalWindow() {
        initComponents();
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        
    }
    
    public void setWindowImage(File f){
        lienzo1.setImage(f);
        this.setMaximumSize(lienzo1.getImagen());
        this.setSize(lienzo1.getImagen());
        this.setTitle(f.toString());
        this.setResizable(false);
    }
    
    public void setWindowThreshold(int i, File file){
        lienzo1.filter(i, file);
        this.setTitle("umbral" + i);
        this.setMaximumSize(lienzo1.getImagen());
        this.setSize(lienzo1.getImagen());
        this.setResizable(false);
        this.setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo1 = new es.ulpgc.dis.practica8.Lienzo();

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.ulpgc.dis.practica8.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
